
["Jujutsu Random Rates"]
	Gojo = 1.0
	Geto = 3.0
	Fushiguro = 4.0
	Maki = 5.0
	Sukuna = 2.0
	Inumaki = 6.0
	Okkotsu = 7.0
	Jogo = 8.0
	Kashimo = 9.0
	Dagon = 10.0
	Tsukumo = 11.0
	Choso = 12.0
	MeiMei = 13.0
	Ishigori = 14.0
	Nanami = 15.0
	Hanami = 16.0
	Mahito = 17.0
	Mahoraga = 18.0
	Takaba = 19.0
	Naoya = 20.0
	Todo = 21.0
	Itadori = 22.0
	Jinichi = 23.0
	Kurourushi = 24.0
	Uraume = 25.0
	Ogi = 26.0
	Higuruma = 27.0
	Angel = 28.0
	Hakari = 29.0
	Miguel = 30.0
	Kusakabe = 31.0
	Chojuro = 32.0
	Yaga = 33.0
	Kugisaki = 34.0
	Junpei = 35.0
	Nishimiya = 36.0
	Dhruv = 37.0
	Yorozu = 38.0
	TakakoUro = 39.0
	SmallpoxDeity = 40.0
	"Ino Takuma" = 41.0

